import { CitationRef } from './types';

export const CITATION_REGISTRY: Record<string, CitationRef> = {
  S1: {
    badge: 'S1',
    label: '[S1]',
    type: 'DATA_SOURCE',
    title: 'Sales Data Ledger (CSV)',
    sourceName: 'Sales Data (CSV) · 78,420 audited rows',
    metric: 'Transaction revenue, SKU velocity & regional channel ledger',
    details: 'Ingested raw transactions from ERP ledger across 6 trailing months. Reconciled with 99.4% cross-table integrity.',
    verified: true,
    auditHash: 'SHA-256: 4f8b9c21e7d012a9',
    targetId: 'src-1',
  },
  S2: {
    badge: 'S2',
    label: '[S2]',
    type: 'DATA_SOURCE',
    title: 'Customer Cohort Analytics (Excel)',
    sourceName: 'Customer Data (Excel) · 42,110 accounts',
    metric: 'Cohort repeat purchase rates, customer tiering & geographic churn history',
    details: 'Validated monthly cohort retention tables joining on Customer ID across regional distributor accounts.',
    verified: true,
    auditHash: 'SHA-256: 8a7d3f10c4e5b982',
    targetId: 'src-2',
  },
  S3: {
    badge: 'S3',
    label: '[S3]',
    type: 'DATA_SOURCE',
    title: 'Marketing Attribution Ledger (CSV)',
    sourceName: 'Marketing Data (CSV) · 21,851 rows',
    metric: 'Ad spend by region, conversion rates, CAC and promo discount records',
    details: 'Direct order attribution tags linking promotional coupon codes with checkout margins.',
    verified: true,
    auditHash: 'SHA-256: 2e9c4b71d8f03a55',
    targetId: 'src-3',
  },
  S4: {
    badge: 'S4',
    label: '[S4]',
    type: 'DATA_SOURCE',
    title: 'Warehouse & ERP Distribution Log',
    sourceName: 'PostgreSQL Inventory Connector · 195,000 SKU logs',
    metric: 'Regional warehouse stock levels, distribution lead times & fulfillment variance',
    details: 'Audited supply chain fulfillment data confirming no supply out-of-stock anomalies occurred.',
    verified: true,
    auditHash: 'SHA-256: 9b2d8f61c3a7e044',
    targetId: 'src-4',
  },
  D1: {
    badge: 'D1',
    label: '[D1]',
    type: 'DATASET_FINDING',
    title: 'Product A Volume Contraction',
    sourceName: 'Sales Data (CSV) · Query #ANOMALY-01',
    metric: '-21.0% volume contraction ($2.38M delta), driving 68.2% of company decline',
    details: 'Internal ledger variance isolation proved that while other products held steady (+0.8% to +2.1%), Product A experienced severe volume drop.',
    verified: true,
    auditHash: 'SHA-256: c1d94f28e5a03b77',
    targetId: 'kf-2',
  },
  D2: {
    badge: 'D2',
    label: '[D2]',
    type: 'DATASET_FINDING',
    title: 'Region South Geographic Epicenter',
    sourceName: 'Sales Data & Regional Logs · Query #ANOMALY-04',
    metric: '-18.4% regional variance, driving 54% of geographic decline',
    details: 'Geographic decomposition isolated Region South as the primary epicenter, while Region West grew +1.2% and North remained stable (-3.1%).',
    verified: true,
    auditHash: 'SHA-256: e8b37c19d4f02a66',
    targetId: 'kf-3',
  },
  D3: {
    badge: 'D3',
    label: '[D3]',
    type: 'DATASET_FINDING',
    title: 'Repeat Customer Churn Escalation',
    sourceName: 'Customer Cohorts (Excel) · Query #COHORT-02',
    metric: '90-day repeat purchase rate fell from 49.0% to 42.8% (-12.7% relative)',
    details: 'Cohort retention analysis proved top-of-funnel acquisition was steady, but existing high-LTV accounts defected after initial purchase.',
    verified: true,
    auditHash: 'SHA-256: 7f3a9e21d8b04c55',
    targetId: 'kf-4',
  },
  D4: {
    badge: 'D4',
    label: '[D4]',
    type: 'DATASET_FINDING',
    title: 'Gross Margin Mix Compression',
    sourceName: 'Financial Ledger · Query #MARGIN-03',
    metric: 'Gross margin contracted 180 bps from 44.2% to 42.4%',
    details: 'High-margin Product A mix share shrunk by 6.4%, transferring volume to lower-margin auxiliary SKUs.',
    verified: true,
    auditHash: 'SHA-256: 3c8e7a12b9d04f66',
    targetId: 'kf-1',
  },
  M1: {
    badge: 'M1',
    label: '[M1]',
    type: 'MARKET_INTEL',
    title: 'Competitor A Promotional Blitz',
    sourceName: 'External Category Tracker & Regional Reports',
    metric: '+18% category promotional share; localized 15-20% discounts in South',
    details: 'Research verified Competitor A initiated aggressive localized price cuts in Month 3, preceding the sharp acceleration in customer churn.',
    verified: true,
    auditHash: 'SHA-256: f4b19c82e7d03a99',
    targetId: 'sig-3',
  },
  M2: {
    badge: 'M2',
    label: '[M2]',
    type: 'MARKET_INTEL',
    title: 'B2B Southern Territory Price Sensitivity',
    sourceName: 'Distributor Field Surveys & Category Analysis',
    metric: 'Customer defection rate to rival bundle is 2.4x higher in price-sensitive tier',
    details: 'Field intelligence confirmed corporate buyers in Bangalore and Chennai shifted procurement to match Competitor A bundled pricing.',
    verified: true,
    auditHash: 'SHA-256: 5a9d3f81c2e7b044',
    targetId: 'sig-1',
  },
  C1: {
    badge: 'C1',
    label: '[C1]',
    type: 'CLAIM',
    title: 'Verified Fact: Top-Line Decline Scope',
    sourceName: 'Claim Graph · CLAIM-017',
    metric: '-$3.05M top-line delta (-14.2%) across trailing 6 months',
    details: 'Reconciled against 12-month trailing moving average. Certified statistically significant with p < 0.001.',
    verified: true,
    auditHash: 'SHA-256: a1b2c3d4e5f60718',
    targetId: 'CLAIM-017',
  },
  C2: {
    badge: 'C2',
    label: '[C2]',
    type: 'CLAIM',
    title: 'Verified Fact: Product A Dominant Contribution',
    sourceName: 'Claim Graph · CLAIM-024',
    metric: 'Product A represents 68.2% of net top-line delta',
    details: 'Variance contribution confirmed. Secondary products (B, C, D) accounted for less than 31.8% combined.',
    verified: true,
    auditHash: 'SHA-256: 1807f6e5d4c3b2a1',
    targetId: 'CLAIM-024',
  },
  C3: {
    badge: 'C3',
    label: '[C3]',
    type: 'CLAIM',
    title: 'Verified Fact: Regional Churn Concentration',
    sourceName: 'Claim Graph · CLAIM-027',
    metric: 'Region South explains 54% of geographic revenue contraction',
    details: 'Statistical correlation with Competitor A promo launch confirmed r = 0.89.',
    verified: true,
    auditHash: 'SHA-256: f1e2d3c4b5a60718',
    targetId: 'CLAIM-027',
  },
  C4: {
    badge: 'C4',
    label: '[C4]',
    type: 'CLAIM',
    title: 'Verified Inference: Competitor Undercutting Mechanism',
    sourceName: 'Claim Graph · CLAIM-030',
    metric: 'Customer defection timing coincides exactly with Competitor A discount blitz',
    details: 'Inference derived from cross-table date join between marketing telemetry and customer repeat purchase drop.',
    verified: true,
    auditHash: 'SHA-256: 2807f6e5d4c3b2a9',
    targetId: 'CLAIM-030',
  },
  C5: {
    badge: 'C5',
    label: '[C5]',
    type: 'CLAIM',
    title: 'Verified Recommendation: Targeted South Intervention',
    sourceName: 'Claim Graph · CLAIM-031',
    metric: 'Option C yields highest risk-adjusted utility (84/100 confidence)',
    details: 'Protects premium pricing in non-affected territories, prevents margin collapse, and respects marketing budget boundaries.',
    verified: true,
    auditHash: 'SHA-256: d8f39a21c7e04b55',
    targetId: 'CLAIM-031',
  },
};
