import { 
  InvestigationState, 
  ChartDataPoint, 
  ProductBreakdown, 
  RegionBreakdown,
  BusinessContext,
  DataSource,
  DataRelationship,
  DecomposedQuestion,
  DynamicInvestigationTask,
  DecisionRoomOption,
  RiskRadarItem,
  OpportunityItem,
  CompetitorInfo,
  TrendItem,
  EmergingSignal
} from './types';

export const PRIMARY_INVESTIGATION: InvestigationState = {
  runId: 'CB-DEMO-001',
  question: 'Our sales have fallen over the last six months. Find the major drivers and recommend what management should do next.',
  timestamp: '2026-09-12 08:52:19 UTC',
  questionType: 'Diagnostic + Prescriptive',
  dataQualityPercent: 91,
  evidenceClaimsCount: 12,
  verifiedClaimsCount: 10,
  warningsCount: 2,
  overallConfidence: 'MEDIUM-HIGH',
  confidenceScore: 84,
  executiveRecommendation: 'Prioritize Product A in Region South and run a controlled pricing/marketing intervention.',
  recommendationExplanation:
    'CorporateBaddie found that the decline is concentrated in Product A and Region South, while external market signals suggest increased competitive pressure.',
  stages: [
    {
      id: 1,
      title: 'Understanding the business question',
      status: 'completed',
      dynamicMessage: 'Understanding what management actually needs to decide...',
      explanation: 'Parsing user prompt into diagnostic root cause vs prescriptive decision scope and evidentiary hurdles.',
      logMessage: 'Business question analyzed and scope bounded',
      durationMs: 800,
    },
    {
      id: 2,
      title: 'Classifying the question',
      status: 'completed',
      dynamicMessage: 'Classifying the analytical taxonomy of the inquiry...',
      explanation: 'Determining question archetype: Diagnostic (why it happened) combined with Prescriptive (what management should do).',
      logMessage: 'Question classified as Diagnostic + Prescriptive',
      durationMs: 750,
    },
    {
      id: 3,
      title: 'Building investigation plan',
      status: 'completed',
      dynamicMessage: 'Identifying which dimensions could explain the decline...',
      explanation: 'Structuring testable hypotheses across product performance, regional demand, pricing elasticity, and customer cohorts.',
      logMessage: 'Investigation plan generated with 5 dimensional hypotheses',
      durationMs: 900,
    },
    {
      id: 4,
      title: 'Profiling business data',
      status: 'completed',
      dynamicMessage: 'Profiling business transaction data and checking completeness...',
      explanation: 'Auditing 284,520 transaction rows across ERP ledgers, CRM records, and regional distributor logs for hygiene and parity.',
      logMessage: 'Data profiling complete: 91% data completeness confirmed',
      durationMs: 950,
      findingsCount: 4,
    },
    {
      id: 5,
      title: 'Calculating core metrics',
      status: 'completed',
      dynamicMessage: 'Calculating revenue trend, margin contribution, and period baselines...',
      explanation: 'Reconciling 6-month trailing revenue contraction (-14.2%) against rolling historical baselines.',
      logMessage: 'Revenue trend identified (-14.2% top-line contraction)',
      durationMs: 850,
    },
    {
      id: 6,
      title: 'Investigating anomalies',
      status: 'completed',
      dynamicMessage: 'Checking whether the decline is concentrated in specific products, regions, or customers...',
      explanation: 'Isolating variance outliers: Product A (-21.0%) and Region South (-18.4%) account for the majority of contraction.',
      logMessage: 'Product and Region dimensions isolated as primary anomaly epicenters',
      durationMs: 1100,
      findingsCount: 4,
    },
    {
      id: 7,
      title: 'Investigating possible root causes',
      status: 'completed',
      dynamicMessage: 'Investigating possible explanations and causal mechanisms...',
      explanation: 'Tracing the causal chain: separates empirical facts (Product A drop) from inferences (channel friction vs pricing elasticity).',
      logMessage: 'Root-cause causal graph constructed',
      durationMs: 1050,
    },
    {
      id: 8,
      title: 'Checking external market context',
      status: 'completed',
      dynamicMessage: 'Checking whether external market conditions support or contradict the internal findings...',
      explanation: 'Cross-referencing category competitor discounting (+18% promotional blitz) and distributor inventory consolidation.',
      logMessage: 'External market research initiated & competitor signals verified',
      durationMs: 1150,
      findingsCount: 3,
    },
    {
      id: 9,
      title: 'Evaluating possible actions',
      status: 'completed',
      dynamicMessage: 'Testing candidate recommendations against available evidence...',
      explanation: 'Scoring Options A, B, and C across capital efficiency, gross margin preservation, operational risk, and strategic feasibility.',
      logMessage: 'Strategic options evaluated: Option C selected as optimal balance',
      durationMs: 1000,
    },
    {
      id: 10,
      title: 'Verifying evidence',
      status: 'completed',
      dynamicMessage: 'Verifying the claims used by the recommendation...',
      explanation: 'Auditing the 12 underlying empirical claims, bounding statistical uncertainty, and verifying ledger reconciliations.',
      logMessage: 'Evidence verification completed (10/12 verified, 2 bounds flagged)',
      durationMs: 900,
      findingsCount: 12,
    },
    {
      id: 11,
      title: 'Building recommendation',
      status: 'completed',
      dynamicMessage: 'Synthesizing executive recommendation and defining reversal triggers...',
      explanation: 'Compiling final executive brief with explicit epistemic boundary conditions: what evidence would change our advice.',
      logMessage: 'Executive recommendation built with falsification boundaries',
      durationMs: 800,
    },
  ],
  keyFindings: [
    {
      id: 'kf-1',
      label: 'Revenue',
      value: '$18.4M',
      change: '↓ 14.2%',
      direction: 'down',
      subtext: 'Last 6 months',
      metricType: 'Enterprise Top-Line',
      evidenceClaimId: 'CLAIM-017',
      detailedData: {
        baseline: '$21.45M (6m prior)',
        current: '$18.40M (current period)',
        variance: '-$3.05M total contraction',
        confidence: 98,
        dataSource: 'Internal ERP Sales Ledger (Table: `fct_daily_revenue_v2`)',
      },
    },
    {
      id: 'kf-2',
      label: 'Product A',
      value: '$7.82M',
      change: '↓ 21.0%',
      direction: 'down',
      subtext: 'Largest contributor to decline',
      metricType: 'Flagship SKU Line',
      evidenceClaimId: 'CLAIM-024',
      detailedData: {
        baseline: '$9.90M',
        current: '$7.82M',
        variance: '-$2.08M (represents 68.2% of total top-line decline)',
        confidence: 94,
        dataSource: 'Product SKU Performance Warehouse (`dim_product_sales`)',
      },
    },
    {
      id: 'kf-3',
      label: 'Region South',
      value: '$4.12M',
      change: '↓ 18.4%',
      direction: 'down',
      subtext: 'Highest regional decline',
      metricType: 'Territory Ledger',
      evidenceClaimId: 'CLAIM-028',
      detailedData: {
        baseline: '$5.05M',
        current: '$4.12M',
        variance: '-$0.93M in territory; Product A velocity dropped 31.4% here',
        confidence: 91,
        dataSource: 'Regional Distribution Telemetry (`fct_territory_sales`)',
      },
    },
    {
      id: 'kf-4',
      label: 'Repeat Customers',
      value: '42.8%',
      change: '↓ 12.7%',
      direction: 'down',
      subtext: 'Potential retention issue',
      metricType: 'Cohort Dynamics',
      evidenceClaimId: 'CLAIM-026',
      detailedData: {
        baseline: '49.0% 90-day repurchase rate',
        current: '42.8% 90-day repurchase rate',
        variance: '-6.2 percentage points (-12.7% relative drop)',
        confidence: 89,
        dataSource: 'Customer 360 CDP (`cohort_retention_curves`)',
      },
    },
  ],
  marketSignals: [
    {
      id: 'mkt-1',
      signal: 'Competitor pricing pressure',
      explanation: 'Competitors in the category have increased promotional activity, offering 15-20% introductory volume rebates in southern industrial hubs.',
      source: 'Demo Market Research / Pricing Benchmarks',
      date: '2026',
      type: 'External Fact',
      impactLevel: 'High',
      confidence: 87,
      isDemoSource: true,
    },
    {
      id: 'mkt-2',
      signal: 'Regional buyer consolidation',
      explanation: 'South region distributor groups merged two centralized procurement committees, extending purchase review cycles from 14 to 38 days.',
      source: 'Supply Chain Trade Intelligence (Demo)',
      date: '2026',
      type: 'External Fact',
      impactLevel: 'Medium',
      confidence: 82,
      isDemoSource: true,
    },
    {
      id: 'mkt-3',
      signal: 'Macro input cost elasticity',
      explanation: 'Enterprise clients are delaying mid-tier SKU replenishment while grandfathering Tier-B software/hardware bundles.',
      source: 'Sector Purchasing Sentiment Survey (Demo)',
      date: '2026',
      type: 'External Fact',
      impactLevel: 'Medium',
      confidence: 79,
      isDemoSource: true,
    },
  ],
  strategicOptions: [
    {
      id: 'A',
      title: 'Reduce prices company-wide',
      description: 'Implement an across-the-board 8-10% price reduction across all four product families and all operational territories.',
      isRecommended: false,
      impact: 'High',
      risk: 'High',
      feasibility: 'Medium',
      scores: {
        impact: 8,
        evidenceStrength: 6,
        feasibility: 6,
        risk: 3, // Lower score = higher risk
        cost: 3, // High gross margin sacrifice
        strategicFit: 4,
      },
      pros: [
        'Immediately neutralizes competitor promotional pricing',
        'Simple to communicate to sales teams and distributors',
      ],
      cons: [
        'Destroys gross margins across healthy products (Product B & D)',
        'Trains enterprise accounts to hold out for permanent price erosion',
        'No targeting for where the bleeding is actually occurring',
      ],
      projectedOutcome: 'Estimated gross margin compression of $2.4M with only 4% volume recovery outside South.',
    },
    {
      id: 'B',
      title: 'Increase marketing spend',
      description: 'Inject $750,000 into top-of-funnel acquisition campaigns and enterprise executive roadshows nationwide.',
      isRecommended: false,
      impact: 'Medium-High',
      risk: 'Medium',
      feasibility: 'High',
      scores: {
        impact: 6,
        evidenceStrength: 5,
        feasibility: 8,
        risk: 6,
        cost: 5,
        strategicFit: 6,
      },
      pros: [
        'Boosts general brand awareness and outbound pipeline count',
        'Leaves current pricing and margin structures intact',
      ],
      cons: [
        'Does not address repeat customer churn or competitor pricing gap',
        'Long payback lag (4-7 months) while sales are actively sliding',
      ],
      projectedOutcome: 'Generates new inbound leads but fails to reverse Product A retention leakage.',
    },
    {
      id: 'C',
      title: 'Target Product A in Region South',
      description: 'Run a controlled, time-bound intervention combining targeted Product A bundling with localized sales incentives in Region South.',
      isRecommended: true,
      impact: 'High',
      risk: 'Medium-Low',
      feasibility: 'High',
      scores: {
        impact: 9,
        evidenceStrength: 9,
        feasibility: 9,
        risk: 8, // Very safe, low downside
        cost: 8, // Highly capital efficient
        strategicFit: 9,
      },
      pros: [
        'Directly attacks the source of 68% of total enterprise contraction',
        'Preserves full price integrity across all other regions and product lines',
        'Fast implementation with measurable weekly check-ins',
        'High evidence grounding from customer churn interviews in South territory',
      ],
      cons: [
        'Requires field sales team alignment and local distributor cooperation',
        'Requires continuous monitoring to prevent cross-border grey market arbitrage',
      ],
      projectedOutcome: 'Projected to recover $1.3M - $1.8M in annualized run-rate within 90 days with <$220k intervention cost.',
    },
  ],
  evidenceClaims: [
    {
      id: 'CLAIM-017',
      title: 'Revenue declined 14.2%',
      type: 'FACT',
      evidence: 'Audited ERP ledger confirms total consolidated revenue fell from $21.45M in prior 6-month half to $18.40M in current half.',
      confidence: 98,
      source: 'Internal ERP Sales Ledger (Table: fct_daily_revenue_v2)',
      verified: true,
      dependencies: [],
    },
    {
      id: 'CLAIM-024',
      title: 'Product A is the primary contributor',
      type: 'FACT',
      evidence: 'Product A contracted $2.08M (-21.0%), accounting for 68.2% of the net $3.05M drop across the portfolio.',
      confidence: 94,
      source: 'Product SKU Performance Warehouse (dim_product_sales)',
      verified: true,
      dependencies: ['CLAIM-017'],
    },
    {
      id: 'CLAIM-028',
      title: 'Region South shows highest decline',
      type: 'FACT',
      evidence: 'Region South sales contracted 18.4% (-$0.93M). Product A sales in South fell 31.4% vs only 8.2% in other regions combined.',
      confidence: 91,
      source: 'Regional Distribution Telemetry (fct_territory_sales)',
      verified: true,
      dependencies: ['CLAIM-017', 'CLAIM-024'],
    },
    {
      id: 'CLAIM-026',
      title: 'Repeat customer retention deteriorated',
      type: 'FACT',
      evidence: '90-day repurchase rates dropped from 49.0% to 42.8% (-12.7% relative decline). Accounts cited competitor promotion.',
      confidence: 89,
      source: 'Customer 360 CDP (cohort_retention_curves)',
      verified: true,
      dependencies: ['CLAIM-017'],
    },
    {
      id: 'CLAIM-030',
      title: 'Competitive pricing pressure increased',
      type: 'EXTERNAL FACT',
      evidence: 'Competitor NexaCorp launched a 15-20% promotional discount in southern territories targeting Product A enterprise tier.',
      confidence: 82,
      source: 'Demo Market Research / Pricing Benchmarks 2026',
      verified: true,
      notes: 'Sampled from distributor survey and public tender bids.',
      dependencies: [],
    },
    {
      id: 'CLAIM-027',
      title: 'Product A decline concentrated in South drives portfolio drop',
      type: 'INFERENCE',
      evidence: 'Statistical variance decomposition links 54% of Product A decline specifically to Region South customer switches.',
      confidence: 86,
      source: 'CorporateBaddie Causal Inference Engine',
      verified: true,
      dependencies: ['CLAIM-024', 'CLAIM-028', 'CLAIM-026'],
    },
    {
      id: 'CLAIM-031',
      title: 'Target Product A in Region South with controlled intervention',
      type: 'RECOMMENDATION',
      evidence: 'Decision matrix evaluation indicates Option C achieves highest risk-adjusted ROI (9.1/10) with minimal margin contagion.',
      confidence: 88,
      source: 'CorporateBaddie Prescriptive Evaluator',
      verified: true,
      dependencies: ['CLAIM-017', 'CLAIM-024', 'CLAIM-028', 'CLAIM-030', 'CLAIM-027'],
    },
    {
      id: 'CLAIM-032',
      title: 'Post-intervention annualized recovery forecast',
      type: 'FORECAST',
      evidence: 'Targeted intervention will recover $1.3M to $1.8M within 90 days assuming competitor pricing remains stable.',
      confidence: 76,
      source: 'Monte Carlo Decision Simulator (1,000 runs)',
      verified: false,
      notes: 'Contains forecast uncertainty; sensitive to competitor counter-reaction.',
      dependencies: ['CLAIM-031'],
    },
  ],
  rootCauseChain: [
    {
      step: 1,
      title: 'Sales decline',
      description: 'Revenue decreased 14.2% over the selected 6-month period across company operations.',
      type: 'FACT',
      evidenceRef: 'CLAIM-017: Internal ERP ledger audit confirms -$3.05M total contraction.',
    },
    {
      step: 2,
      title: 'Product A decline',
      description: 'Product A contributed the largest share of the decline (68.2% of net loss, -21.0% volume).',
      type: 'FACT',
      evidenceRef: 'CLAIM-024: SKU performance ledger reflects -$2.08M contraction.',
    },
    {
      step: 3,
      title: 'Region South concentration',
      description: 'The concentration of the decline suggests Product A in Region South is the primary failure node.',
      type: 'INFERENCE',
      evidenceRef: 'CLAIM-027: Product A velocity collapsed 31.4% in South, compared to -8.2% in other zones.',
    },
    {
      step: 4,
      title: 'Repeat customer decline',
      description: 'Existing customer cohort repurchase rates plummeted 12.7%, reflecting account churn rather than top-of-funnel drop.',
      type: 'FACT',
      evidenceRef: 'CLAIM-026: 90-day repurchase dropped from 49.0% to 42.8%.',
    },
    {
      step: 5,
      title: 'Possible competitive/pricing pressure',
      description: 'Competitive pricing pressure has increased in the relevant market, offering lower barriers to entry.',
      type: 'EXTERNAL FACT',
      evidenceRef: 'CLAIM-030: External demo research indicates 15-20% competitor promotional incentives.',
    },
  ],
  conditionShifts: [
    'Product A recovered without intervention (e.g. if backlogged orders clear naturally in next 30 days).',
    'Region South decline was caused by a temporary event (e.g. extreme local logistics disruption or warehouse relocation).',
    'Competitor pricing returned to normal (e.g. if rival promotional campaign was a short-lived fiscal year-end blitz).',
    'Margin impact from intervention became unacceptable (e.g. if distributor co-funding exceeds 25% gross margin threshold).',
  ],
  risksAndLimitations: [
    'Demo Dataset: Analysis executed on synthetic enterprise transaction datasets for prototype validation.',
    'External Evidence May Change: Competitor promotional tracking is grounded in demo market sources.',
    'Correlation Does Not Prove Causation: The statistical association between competitor discounts and South churn requires controlled A/B verification.',
    'Forecast Confidence Depends on Historical Data: 90-day recovery projection carries a ±18% standard error band.',
    'Human Review Required: CorporateBaddie provides prescriptive intelligence; management retains sole fiduciary authority.',
  ],
};

export const MOCK_CHART_SERIES: ChartDataPoint[] = [
  { period: 'Month 1', revenue: 3.65, baseline: 3.60, productA: 1.72, productOthers: 1.93, repeatCustomers: 51.2, newCustomers: 14.8 },
  { period: 'Month 2', revenue: 3.52, baseline: 3.62, productA: 1.64, productOthers: 1.88, repeatCustomers: 49.8, newCustomers: 14.5 },
  { period: 'Month 3', revenue: 3.28, baseline: 3.65, productA: 1.48, productOthers: 1.80, repeatCustomers: 47.4, newCustomers: 14.1 },
  { period: 'Month 4', revenue: 3.05, baseline: 3.68, productA: 1.30, productOthers: 1.75, repeatCustomers: 45.1, newCustomers: 13.9 },
  { period: 'Month 5', revenue: 2.98, baseline: 3.70, productA: 1.22, productOthers: 1.76, repeatCustomers: 43.6, newCustomers: 13.8 },
  { period: 'Month 6', revenue: 2.82, baseline: 3.72, productA: 1.12, productOthers: 1.70, repeatCustomers: 42.8, newCustomers: 13.5 },
];

export const MOCK_PRODUCTS: ProductBreakdown[] = [
  { name: 'Product A', revenue: 7.82, share: 42.5, growth: -21.0, flag: 'Primary Drag (-68% net loss)' },
  { name: 'Product B', revenue: 5.10, share: 27.7, growth: +2.1, flag: 'Resilient / Stable' },
  { name: 'Product C', revenue: 3.42, share: 18.6, growth: -3.4, flag: 'Within normal tolerance' },
  { name: 'Product D', revenue: 2.06, share: 11.2, growth: +0.8, flag: 'Slight positive' },
];

export const MOCK_REGIONS: RegionBreakdown[] = [
  { name: 'Region South', revenue: 4.12, share: 22.4, growth: -18.4, flag: 'Severe Underperformance' },
  { name: 'Region North', revenue: 6.20, share: 33.7, growth: -3.1, flag: 'Minor contraction' },
  { name: 'Region West', revenue: 4.88, share: 26.5, growth: +1.2, flag: 'Positive trajectory' },
  { name: 'Region East', revenue: 3.20, share: 17.4, growth: -2.0, flag: 'Stable' },
];

export const EXAMPLE_QUESTIONS = [
  {
    title: 'Why are our sales declining?',
    prompt: 'Our sales have fallen over the last six months. Find the major drivers and recommend what management should do next.',
  },
  {
    title: 'Which products should we prioritize?',
    prompt: 'Which products should we prioritize across our regional channels to maximize high-margin growth in Q3/Q4?',
  },
  {
    title: 'Which region has the biggest growth opportunity?',
    prompt: 'Evaluate our performance by territory to identify which region has the highest untapped expansion potential versus risk.',
  },
  {
    title: 'Should we reduce prices or increase marketing?',
    prompt: 'Should we reduce prices or increase marketing spend to counter emerging competitor promotional pressure?',
  },
];

export const DEFAULT_BUSINESS_CONTEXT: BusinessContext = {
  companyName: 'Demo Retail Co.',
  industry: 'E-commerce',
  primaryMarket: 'India',
  businessObjective: 'Increase profitable revenue',
  currentStrategy: 'Premium product positioning',
  knownConstraints: 'Limited marketing budget',
  importantKpis: ['Revenue', 'Gross Margin', 'Customer Retention', 'Average Order Value'],
  managementPriorities: 'Improve profitability without losing customers',
};

export const DEFAULT_DATA_SOURCES: DataSource[] = [
  {
    id: 'src-1',
    name: 'Sales Data',
    type: 'CSV',
    status: 'Connected',
    recordsCount: 78420,
    fieldsCount: 11,
    selected: true,
    description: 'Consolidated transactional revenue, SKU velocity & regional channel ledger',
  },
  {
    id: 'src-2',
    name: 'Customer Data',
    type: 'Excel',
    status: 'Connected',
    recordsCount: 42110,
    fieldsCount: 9,
    selected: true,
    description: 'Cohort repeat purchase rates, customer tiering & geographic churn history',
  },
  {
    id: 'src-3',
    name: 'Marketing Data',
    type: 'CSV',
    status: 'Connected',
    recordsCount: 21851,
    fieldsCount: 7,
    selected: true,
    description: 'Ad spend by region, conversion rates, CAC and promotional discount records',
  },
  {
    id: 'src-4',
    name: 'Warehouse & ERP Database',
    type: 'Database',
    status: 'Ready',
    recordsCount: 195000,
    fieldsCount: 34,
    selected: false,
    description: 'PostgreSQL connector to regional distribution center inventory levels',
  },
  {
    id: 'src-5',
    name: 'Competitor Price Tracker API',
    type: 'API',
    status: 'Ready',
    recordsCount: 12400,
    fieldsCount: 8,
    selected: false,
    description: 'Live webhook scraping category pricing across e-commerce & retail portals',
  },
  {
    id: 'src-6',
    name: 'Q4 Strategic Retrospective',
    type: 'Previous Analysis',
    status: 'Ready',
    recordsCount: 1,
    fieldsCount: 14,
    selected: false,
    description: 'CorporateBaddie run CB-DEMO-000 historical baseline and variance logs',
  },
];

export const DATA_RELATIONSHIPS: DataRelationship[] = [
  {
    key: 'Customer ID',
    description: 'Joins Sales Data transactions with Customer cohort profiles and retention history',
    sources: ['Sales Data (CSV)', 'Customer Data (Excel)'],
  },
  {
    key: 'Order ID',
    description: 'Links marketing campaign attribution tags directly to checkout basket ledgers',
    sources: ['Sales Data (CSV)', 'Marketing Data (CSV)'],
  },
  {
    key: 'Product ID',
    description: 'Maps SKU item numbers to unit margins, category velocity, and returns',
    sources: ['Sales Data (CSV)', 'Warehouse & ERP Database'],
  },
  {
    key: 'Date',
    description: 'Harmonizes time series across weekly sales, monthly churn, and competitor promo blitzes',
    sources: ['Sales Data (CSV)', 'Customer Data (Excel)', 'Marketing Data (CSV)'],
  },
];

export const DECOMPOSED_QUESTIONS: DecomposedQuestion[] = [
  {
    id: 1,
    question: 'How large is the decline?',
    status: 'Answered',
    evidenceFound: '-14.2% top-line contraction totaling -$3.05M delta against rolling 12-month baseline.',
    confidence: 'High',
    claimRef: 'CLM-017',
  },
{
     id: 2,
     question: 'When did the decline begin?',
     status: 'Answered',
     evidenceFound: 'Began in Month 3, accelerating steeply in Months 4-6 following competitor campaigns.',
     confidence: 'High',
     claimRef: 'CLM-017',
   },
  {
    id: 3,
    question: 'Which products are responsible?',
    status: 'Answered',
    evidenceFound: 'Product A accounts for 68.2% of net top-line delta (-21.0% volume contraction).',
    confidence: 'High',
    claimRef: 'CLM-024',
  },
  {
    id: 4,
    question: 'Which regions are affected?',
    status: 'Answered',
    evidenceFound: 'Region South is the geographic epicenter, down -18.4% compared to +1.2% in West.',
    confidence: 'High',
    claimRef: 'CLM-027',
  },
  {
    id: 5,
    question: 'Has customer behavior changed?',
    status: 'Answered',
    evidenceFound: 'Existing customer cohort repeat purchase rate dropped from 49.0% to 42.8% (-12.7%).',
    confidence: 'High',
    claimRef: 'CLM-026',
  },
  {
    id: 6,
    question: 'Has profitability changed?',
    status: 'Answered',
    evidenceFound: 'Gross margin contracted 180 bps as high-margin Product A mix share shrunk by 6.4%.',
    confidence: 'High',
    claimRef: 'CLM-028',
  },
  {
    id: 7,
    question: 'Are there external market signals?',
    status: 'Answered',
    evidenceFound: 'Competitor A launched aggressive 15-20% promotional discounts in South corridors.',
    confidence: 'Medium-High',
    claimRef: 'CLM-030',
  },
  {
    id: 8,
    question: 'What strategic options are available?',
    status: 'Answered',
    evidenceFound: 'Option A (Company-wide price cuts), Option B (Marketing expansion), Option C (Targeted South intervention).',
    confidence: 'High',
    claimRef: 'CLM-031',
  },
  {
    id: 9,
    question: 'Which option has the strongest evidence?',
    status: 'Answered',
    evidenceFound: 'Option C exhibits highest risk-adjusted utility (84/100) protecting premium positioning and budget constraints.',
    confidence: 'High',
    claimRef: 'CLM-031',
  },
];

export const DYNAMIC_PLAN_TASKS: DynamicInvestigationTask[] = [
  {
    id: 'task-1',
    title: 'Analyze revenue trend',
    isInitial: true,
    status: 'completed',
    evidenceOutcome: 'Identified -14.2% top-line contraction over trailing 6 months',
  },
  {
    id: 'task-2',
    title: 'Analyze product performance',
    isInitial: true,
    status: 'completed',
    evidenceOutcome: 'Isolated Product A as 68.2% contributor to total company variance',
  },
  {
    id: 'task-3',
    title: 'Analyze regional performance',
    isInitial: true,
    status: 'completed',
    evidenceOutcome: 'Region South detected as 54% of regional performance variance',
  },
  {
    id: 'task-4',
    title: 'Analyze customer behavior',
    isInitial: true,
    status: 'completed',
    evidenceOutcome: 'Discovered repeat buyer cohort retention degradation (-12.7%)',
  },
  {
    id: 'task-5',
    title: 'Investigate Product A margin',
    isInitial: false,
    status: 'discovered',
    discoveredReason: 'Triggered by Product A revenue contribution divergence exceeding threshold (>50%)',
    evidenceOutcome: 'Gross margin fell from 44.2% to 41.8% due to un-targeted channel discounting',
  },
  {
    id: 'task-6',
    title: 'Compare Product A pricing',
    isInitial: false,
    status: 'discovered',
    discoveredReason: 'Triggered by external competitor promotion vector detected in target category',
    evidenceOutcome: 'Product A priced 18% above Competitor A promo bundle in target territory',
  },
  {
    id: 'task-7',
    title: 'Investigate Region South customer retention',
    isInitial: false,
    status: 'discovered',
    discoveredReason: 'Triggered by regional variance concentration in Region South cohort ledgers',
    evidenceOutcome: 'South repeat buyers defecting to competitor bundle at 2.4x higher rate',
  },
];

export const DECISION_ROOM_OPTIONS: DecisionRoomOption[] = [
  {
    id: 'opt-1',
    name: 'Targeted Pricing & Regional Intervention',
    isRecommended: true,
    expectedImpact: '+₹18.4L / month revenue recovery (+8.2%)',
    evidenceStrength: 'Strong',
    cost: '₹2.8L / month (Targeted promo & co-op marketing)',
    risk: 'Low',
    feasibility: 'High',
    timeToImpact: '30 - 45 days',
    strategicFit: 'High',
    confidence: 84,
    whyThisOption: {
      supportingEvidence: [
        'Isolates Product A in Region South, where 68.2% of total business decline originated [CLM-024, CLM-027].',
        'Directly counters Competitor A localized 15-20% promotional discounts without devaluing other regions [CLM-030].',
        'Preserves company gross margin floor (minimum 38%) and respects limited marketing budget constraints.',
      ],
      potentialUpside: 'Restores South repurchase rates from 42.8% back toward 48% within 60 days, recovering ~₹55L quarterly ARR.',
      risks: [
        'Cross-regional gray market arbitrage if regional discount exceeds 15%.',
        'Distributor margin pushback if co-op marketing incentives are delayed.',
      ],
      dependencies: [
        'Regional distributor sign-off on co-funded incentive structure in Region South.',
        'Marketing team ready with localized South messaging highlighting premium feature superiority.',
      ],
      whatMustBeTrue: [
        'Customer demand elasticity in Region South responds to value bundle vs raw price cut.',
        'Competitor A does not escalate price war into North and West regions.',
        'Product A inventory in Southern distribution hubs can handle +12% volume lift.',
      ],
    },
  },
  {
    id: 'opt-2',
    name: 'Marketing Expansion (Broad-Scale Awareness)',
    isRecommended: false,
    expectedImpact: '+₹11.2L / month revenue (+4.8%)',
    evidenceStrength: 'Moderate',
    cost: '₹8.5L / month (High digital acquisition spend)',
    risk: 'Medium',
    feasibility: 'Medium',
    timeToImpact: '60 - 90 days',
    strategicFit: 'Medium',
    confidence: 62,
    whyThisOption: {
      supportingEvidence: [
        'Top-of-funnel traffic has remained relatively stable; issue is churn among existing buyers [CLM-026].',
        'Violates management constraint on limited marketing budget and does not address localized pricing friction in South.',
      ],
      potentialUpside: 'Increases brand visibility across India, lifting Product B and C top-of-funnel conversion.',
      risks: [
        'Dilutes ROAS if advertising pours into territories experiencing severe price-undercutting.',
        'High cash burn without resolving repeat customer defection.',
      ],
      dependencies: ['Substantial marketing budget authorization (>₹25L quarterly).'],
      whatMustBeTrue: ['CAC remains below ₹420 per converted account in an aggressive bidding climate.'],
    },
  },
  {
    id: 'opt-3',
    name: 'Product Portfolio Change (Accelerate Product B & C)',
    isRecommended: false,
    expectedImpact: '+₹14.0L / month revenue (+6.1%)',
    evidenceStrength: 'Moderate',
    cost: '₹5.0L / month (R&D & SKU re-tooling)',
    risk: 'Medium',
    feasibility: 'Low',
    timeToImpact: '120 - 180 days',
    strategicFit: 'Medium',
    confidence: 58,
    whyThisOption: {
      supportingEvidence: [
        'Product B is growing (+2.1%) and Product C is stable, but cannot offset Product A 42.5% revenue weight in short term.',
        'High execution lag time makes it ineffective for reversing trailing 6-month contraction.',
      ],
      potentialUpside: 'Diversifies company revenue away from Product A dependency over 12-18 months.',
      risks: ['Product A continues contracting unmitigated while new lines ramp up.'],
      dependencies: ['Product engineering and supply chain lead times of 3-6 months.'],
      whatMustBeTrue: ['Product B margins can sustain higher production volume without unit cost spikes.'],
    },
  },
  {
    id: 'opt-4',
    name: 'Do Nothing (Observe Organic Recovery)',
    isRecommended: false,
    expectedImpact: 'Negative: Ongoing -₹4.2L / month contraction',
    evidenceStrength: 'Weak',
    cost: '₹0 direct expenditure',
    risk: 'High',
    feasibility: 'High',
    timeToImpact: 'Immediate',
    strategicFit: 'Low',
    confidence: 25,
    whyThisOption: {
      supportingEvidence: [
        'Decline has worsened across three consecutive periods (-14.8% -> -18.2% -> -21.0%) with zero stabilization [CLM-017].',
        'Competitor promotional activity is compounding customer habituation to rival alternatives.',
      ],
      potentialUpside: 'Avoids cash expenditure and prevents margin erosion if market churn reverses on its own.',
      risks: [
        'Permanent market share surrender to Competitor A in key industrial hubs.',
        'Loss of critical distributor shelf space and high-value customer relationships.',
      ],
      dependencies: ['None.'],
      whatMustBeTrue: ['Competitor A promotional blitz terminates within 30 days due to competitor insolvency or capital depletion.'],
    },
  },
];

export const RISK_RADAR_ITEMS: RiskRadarItem[] = [
  {
    category: 'Market Risk',
    level: 'MEDIUM',
    evidence: 'Competitive activity is increasing in target category (+18% category promotional share).',
    mitigation: 'Run a controlled regional intervention before scaling.',
  },
  {
    category: 'Data Risk',
    level: 'LOW-MEDIUM',
    evidence: 'Some customer records are incomplete (missing 9% demographic tags in West territory).',
    mitigation: 'Validate customer-level retention metrics before execution.',
  },
  {
    category: 'Financial Risk',
    level: 'MEDIUM',
    evidence: 'Broad discounting could erode gross margins below the 38% hurdle rate.',
    mitigation: 'Cap pricing incentives strictly to Product A bundles in Region South with co-op distributor offsets.',
  },
  {
    category: 'Customer Risk',
    level: 'HIGH',
    evidence: 'Repeat customer cohort retention has dropped 12.7% over the last 90 days.',
    mitigation: 'Deploy targeted loyalty incentives and personalized account check-ins to prevent customer defection.',
  },
  {
    category: 'Execution Risk',
    level: 'LOW',
    evidence: 'Regional sales ops and distributor partnerships are already active in target zones.',
    mitigation: 'Pilot intervention with top 5 regional distributors before territorial rollout.',
  },
  {
    category: 'Operational Risk',
    level: 'LOW-MEDIUM',
    evidence: 'Warehouse inventory in South requires buffer stock to support potential +12% volume recovery.',
    mitigation: 'Pre-position 2,500 units of Product A in Bangalore distribution hub prior to campaign launch.',
  },
];

export const OPPORTUNITY_RADAR_ITEMS: OpportunityItem[] = [
  {
    id: 'opp-1',
    category: 'Product',
    title: 'Product B shows strong growth but low marketing exposure',
    description: 'Product B grew +2.1% despite receiving only 8% of total marketing allocation. Highly resilient unit economics.',
    potentialImpact: '+₹18L - ₹24L incremental ARR',
    evidenceStrength: 'Strong',
    confidence: 88,
    recommendedNextStep: 'Reallocate 15% of generic brand ad spend to Product B search and display campaigns.',
    filterTags: ['Revenue', 'Profit', 'Products'],
  },
  {
    id: 'opp-2',
    category: 'Regional',
    title: 'Region West has strong customer growth and relatively low competition',
    description: 'Region West achieved +1.2% growth with low rival promotional pressure and highest repeat buyer loyalty (52%).',
    potentialImpact: '+14% territorial revenue expansion',
    evidenceStrength: 'Strong',
    confidence: 82,
    recommendedNextStep: 'Accelerate distributor onboarding and partner incentives in Maharashtra and Gujarat corridors.',
    filterTags: ['Revenue', 'Regions', 'Market'],
  },
  {
    id: 'opp-3',
    category: 'Customer',
    title: 'High-value customers show strong repeat-purchase potential',
    description: 'Top 15% of customer accounts have 3.4x higher LTV and remain loyal when provided exclusive bundle perks.',
    potentialImpact: '+22% retention uplift',
    evidenceStrength: 'Strong',
    confidence: 86,
    recommendedNextStep: 'Launch dedicated VIP retention program with priority delivery and customized replenishment terms.',
    filterTags: ['Customers', 'Profit'],
  },
  {
    id: 'opp-4',
    category: 'Margin',
    title: 'Product C has strong demand but unusually high discounting',
    description: 'Product C averages 24% off MSRP despite steady organic demand. Price elasticity suggests low sensitivity to discount reduction.',
    potentialImpact: '+210 bps gross margin recovery',
    evidenceStrength: 'Moderate',
    confidence: 78,
    recommendedNextStep: 'Cap maximum distributor discount on Product C at 12%, immediately reclaiming margin.',
    filterTags: ['Profit', 'Products', 'Revenue'],
  },
];

export const COMPETITOR_LANDSCAPE: CompetitorInfo[] = [
  {
    name: 'Competitor A',
    pricing: 'Aggressive: 15-20% localized promo discounts',
    promotion: 'Heavy digital blitz & regional distributor incentives',
    productPosition: 'Direct premium alternative targeting Product A',
    marketSignal: '+18% category promotional share in Q2',
    correlatedInternalFinding: 'Directly correlates with -31.4% Product A volume collapse in Region South.',
  },
  {
    name: 'Competitor B',
    pricing: 'Stable / Premium parity with Demo Retail Co.',
    promotion: 'Focused on enterprise B2B contracts',
    productPosition: 'Institutional & enterprise supply',
    marketSignal: 'Steady market share across North and West',
    correlatedInternalFinding: 'Explains why Region North has remained relatively stable (-3.1%).',
  },
  {
    name: 'Competitor C',
    pricing: 'Value tier / budget packaging',
    promotion: 'Low / sporadic discount coupons',
    productPosition: 'Entry-level consumers with lower build quality',
    marketSignal: 'Minimal market movement in premium segments',
    correlatedInternalFinding: 'No meaningful customer cannibalization detected among high-LTV accounts.',
  },
];

export const TREND_RADAR_ITEMS: TrendItem[] = [
  { metric: 'Revenue', status: 'Declining', detail: '-14.2% top-line contraction over trailing 6 months (-$3.05M total variance).' },
  { metric: 'Customer behavior', status: 'Declining', detail: 'Repeat cohort repurchase rate slipped from 49.0% to 42.8% (-12.7% drop).' },
  { metric: 'Product demand', status: 'Declining', detail: 'Product A volume dropped -21.0%; other product lines remain resilient (+0.8% to +2.1%).' },
  { metric: 'Pricing', status: 'Emerging', detail: 'Market pricing pressure intensifying; category rivals running localized 15-20% discounts.' },
  { metric: 'Margins', status: 'Declining', detail: 'Gross margin compressed by 180 bps due to loss of high-margin Product A sales mix.' },
  { metric: 'Market activity', status: 'Increasing', detail: 'Competitor promotional intensity up +18% in Southern regional corridors.' },
];

export const EMERGING_SIGNALS: EmergingSignal[] = [
  {
    id: 'sig-1',
    title: 'Repeat customer decline is accelerating',
    signalType: 'Customer Retention Risk',
    evidence: '90-day repurchase rate dropped from 49.0% to 42.8% across three consecutive cohorts [CLM-026].',
    confidence: 'High',
    recommendedInvestigation: 'Conduct structured customer feedback interviews with 50 recently churned southern distributor accounts.',
  },
  {
    id: 'sig-2',
    title: 'Product A demand has weakened for three consecutive periods',
    signalType: 'Product Lifecycle Friction',
    evidence: 'Monthly contraction progressed from -14.8% -> -18.2% -> -21.0% [CLM-024].',
    confidence: 'High',
    recommendedInvestigation: 'Analyze SKU feature parity against Competitor A latest bundle release.',
  },
  {
    id: 'sig-3',
    title: 'Competitor promotional activity appears to be increasing',
    signalType: 'External Market Pressure',
    evidence: '3 independent external signals confirm localized 15-20% promotional incentives [CLM-030].',
    confidence: 'Medium',
    recommendedInvestigation: 'Track whether Competitor A promotional blitz transitions into permanent MSRP repricing.',
  },
];

export const GROUNDED_QA_PAIRS = [
  {
    question: 'Why did you recommend Product A?',
    answer:
      'CorporateBaddie recommended Product A because it represents 42.5% of total company revenue and accounted for 68.2% of the net top-line decline [CLM-024]. While Product B and D are stable, reversing the business decline requires addressing the primary driver rather than secondary lines.',
    referencedClaims: ['CLM-017', 'CLM-024'],
  },
  {
    question: 'Show me the evidence for Region South.',
    answer:
      'In Region South, sales declined by -18.4% [CLM-027], and Product A velocity fell -31.4%—more than three times the rate of any other territory. Furthermore, external market intelligence verified that Competitor A launched a localized 15-20% promotional blitz in this specific territory [CLM-030].',
    referencedClaims: ['CLM-027', 'CLM-030'],
  },
  {
    question: "What if we don't reduce prices?",
    answer:
      'If prices are not adjusted, the scenario simulator and causal chain project an ongoing -₹4.2L/month top-line erosion as repeat buyers continue defecting to Competitor A [CLM-026]. However, CorporateBaddie specifically advises against company-wide price cuts—recommending instead a targeted regional value bundle in Region South to preserve overall gross margin.',
    referencedClaims: ['CLM-026', 'CLM-031'],
  },
  {
    question: 'Which customers are most at risk?',
    answer:
      'Existing repeat customers in Region South represent the highest immediate risk. Cohort repurchase rates plummeted from 49.0% to 42.8% (-12.7%) [CLM-026], indicating defection to cheaper rival bundles rather than top-of-funnel acquisition failure.',
    referencedClaims: ['CLM-026', 'CLM-028'],
  },
  {
    question: 'What would happen if marketing budget increased?',
    answer:
      'Simulations indicate broad marketing expansion would only deliver +4.8% revenue recovery at a high cost of ₹8.5L/month [CLM-031]. Because top-of-funnel discovery remains healthy, spending marketing dollars without fixing the price/value friction in Region South yields poor ROAS.',
    referencedClaims: ['CLM-026', 'CLM-031'],
  },
];

